---
- name: Update and upgrade all packages
  apt:
    name: "*"
    state: latest
    update_cache: yes 
    force_apt_get: yes

- name: Download dpkg packages zabbix-release
  get_url:
    url: "{{ download_dpkg }}"
    dest: "{{ path_download }}"

- name: Install a .deb package
  ansible.builtin.apt:
    deb: "{{ path_download }}/zabbix-release_5.4-1+debian11_all.deb"

- name: Update all packages
  apt:
    name: "*"
    state: latest
    update_cache: yes 
    force_apt_get: yes

- name: Install packages for Zabbix
  apt: 
    name: "{{ zabbix_packages }}"
    state: latest 
    update_cache: yes 

- name: Started and Enabled MariaDB 
  service: 
    name: mariadb 
    enabled: true 
    state: started 

- name: Settings MariaDB | Configure root password for MariaDB 
  command: 
    cmd: mysqladmin -u root password {{ mariadb_root_pass }}

- name: Settings MariaDB | Create DB for Zabbix
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    encoding: utf8
    collation: utf8_bin
    login_user: root 
    login_password: "{{ mariadb_root_pass }}"
  failed_when: false 

- name: Settings MariaDB | Create User for Zabbix
  community.mysql.mysql_user:
    name: "{{ db_user_name }}"
    password: "{{ db_user_pass }}"
    priv: '*.*:ALL,GRANT'
    host: '%'
    state: present
    login_user: root
    login_password: "{{ mariadb_root_pass }}"

- name: Settings MariaDB | Import DB for Zabbix
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    encoding: utf8
    collation: utf8_bin
    target: "{{ destin_folder_import_db_zabbix }}"
    state: import
    login_user: "{{ db_user_name }}" 
    login_password: "{{ db_user_pass }}"
  failed_when: false 

- name: Configure zabbix_server.conf
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_server.conf
    regexp: ^# DBPassword=
    line: DBPassword={{ db_user_pass }}

- name: Remove NGINX default file
  file: 
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Configure NGINX for Zabbix
  ansible.builtin.lineinfile:
    path: /etc/zabbix/nginx.conf
    regexp: ^#        listen          80;
    line:         listen          80;

- name: Configure NGINX for Zabbix
  ansible.builtin.lineinfile:
    path: /etc/zabbix/nginx.conf
    regexp: ^#        server_name     example.com;
    line: server_name          {{ ansible_ssh_host }};  
  notify: 
    - Start and enable services zabbix

- debug:
    msg:
      - Open the browser 'http://{{ ansible_ssh_host }}' 
      - "#######################################################"
      - "### Password user database --->  {{ db_user_pass }} ###"
      - "#######################################################"
      - "### Authentication default on platform:   #############"
      - "### login: Admin                          #############"
      - "### password: zabbix                      #############"
      - "#######################################################"
